image: gcc

before_script:
    - apt update && apt install -y cmake libhdf5-serial-dev

stages:
  - build
  - test
  - pack

build:octreegen:
    stage: build
    only:
        - pushes
    script:
        - cd octreegen
        - mkdir build
        - cd build
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$ARCH
        - make -j4
    artifacts:
        untracked: true
        expire_in: 1h

test:octreegen:
    stage: test
    dependencies:
        - build:octreegen
    only:
        - pushes
    script:
        - cd octreegen/build
        - ./tests


pack:octreegen:
    stage: pack
    dependencies:
        - build:octreegen
    only:
        - tags
    before_script:
        - apt update && apt install -y cmake
    script:
        - cd octreegen/build
        - make package
        - mv *.deb ..
        - echo "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/octreegen-$CI_COMMIT_TAG-$ARCH.deb?job=$CI_JOB_NAME"
    artifacts:
        paths:
            - "*.deb"
