image: gcc

before_script:
    - apt update && apt install -y cmake libhdf5-serial-dev qtbase5-dev doxygen graphviz

stages:
  - buildlib
  - build
  - test
  - pack
  - doc

build:liboctree:
    stage: buildlib
    only:
        - pushes
    script:
        - cd liboctree
        - mkdir build
        - cd build
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$ARCH
        - make -j4
    artifacts:
        untracked: true
        expire_in: 1h


build:octreegen:
    stage: build
    dependencies:
        - build:liboctree
    only:
        - pushes
    script:
        - cd liboctree/build
        - make install
        - cd ../../octreegen
        - mkdir build
        - cd build
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$ARCH
        - make -j4
    artifacts:
        untracked: true
        expire_in: 1h

build:octreegen-gui:
    stage: build
    only:
        - pushes
    script:
        - cd octreegen-gui
        - mkdir build
        - cd build
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$ARCH
        - make -j4
    artifacts:
        untracked: true
        expire_in: 1h


test:liboctree:
    stage: test
    dependencies:
        - build:liboctree
    only:
        - pushes
    script:
        - cd liboctree/build
        - ./tests

test:octreegen:
    stage: test
    dependencies:
        - build:octreegen
    only:
        - pushes
    script:
        - cd liboctree/build
        - make install
        - ldconfig
        - cd ../../octreegen/build
        - ./tests


pack:liboctree:
    stage: pack
    dependencies:
        - build:liboctree
    only:
        - tags
    script:
        - cd liboctree/build
        - make package
        - mv *.deb ../..
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - echo "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/liboctree-$CI_COMMIT_TAG-$ARCH.deb?job=$CI_JOB_NAME"
    artifacts:
        paths:
            - "*.deb"

pack:octreegen:
    stage: pack
    dependencies:
        - build:octreegen
    only:
        - tags
    script:
        - cd liboctree/build
        - make install
        - cd ../../octreegen/build
        - make package
        - mv *.deb ../..
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - echo "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/octreegen-$CI_COMMIT_TAG-$ARCH.deb?job=$CI_JOB_NAME"
    artifacts:
        paths:
            - "*.deb"

pack:octreegen-gui:
    stage: pack
    dependencies:
        - build:octreegen-gui
    only:
        - tags
    script:
        - cd octreegen-gui/build
        - make package
        - mv *.deb ../..
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - echo "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/octreegen-gui-$CI_COMMIT_TAG-$ARCH.deb?job=$CI_JOB_NAME"
    artifacts:
        paths:
            - "*.deb"

pages:
    stage: doc
    only:
        - tags
    script:
        - cd liboctree/build
        - make doc
        - mv ./html/ ../../public/
    artifacts:
        paths:
            - public
