image: gcc

before_script:
    - apt update && apt install -y cmake libhdf5-serial-dev

stages:
  - build
  - test
  - pack

octreegen:
    stage: build
    only:
        - pushes
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j4
    artifacts:
        untracked: true

test:
    stage: test
    dependencies:
        - build
    only:
        - pushes
    script:
        - ls
        - cd build
        - ./tests


pack:
    stage: pack
    dependencies:
        - build
    only:
        - tags
    script:
        - ls
        - cd build
        - ARCH=$(echo $CI_RUNNER_EXECUTABLE_ARCH | tr / _)
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$ARCH
        - make package
        - mv *.deb ..
        - echo "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/octreegen-$CI_COMMIT_TAG-$ARCH.deb?job=$CI_JOB_NAME"
    artifacts:
        paths:
            - "*.deb"
