image: gcc

before_script:
    - apt update && apt install -y cmake

tests:
    only:
        - pushes
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j4
        - make test
