image: gcc

before_script:
    - apt update && apt install -y cmake libhdf5-serial-dev

tests:
    only:
        - pushes
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j4
        - ./tests
          # a few tests before setting things nicer
        - echo $CI_RUNNER_EXECUTABLE_ARCH
        - echo $CI_PROJECT_PATH
        - echo $CI_PROJECT_PATH_SLUG
        - echo $CI_PROJECT_URL
        - echo $CI_JOB_NAME


build:
    only:
        - tags
    script:
        - mkdir build
        - cd build
        - cmake .. -DTAG=$CI_COMMIT_TAG -DARCH=$CI_RUNNER_EXECUTABLE_ARCH
        - make package
        - mv *.deb ..
    artifacts:
        paths:
            - "*.deb"

# https://gitlab.com/Dexter9313/octree-file-format/-/jobs/artifacts/0.0.1/raw/octreegen-0.0.1-unknown.deb?job=build
